language: php

php:
  - 5.6
  - 7.0
#  - hhvm
addons:
  firefox: "45.0"

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.1"
  - travis_retry composer update --dev --prefer-dist --no-interaction
# setup application:
  - |
    sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" config/web.php
  # - chmod +x ./tests/travis/setup.sh
  # - ./tests/travis/setup.sh
before_script:
  - firefox --version
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

  - wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
  - java -jar selenium-server-standalone-2.53.1.jar > /dev/null &
  # - java -jar selenium-server-standalone-3.0.1.jar > /dev/null &
  # - java -jar -Dwebdriver.gecko.driver=geckodriver selenium-server-standalone-2.53.1.jar > /dev/null &
  - sleep 20
  - tests/bin/yii serve &
  - sleep 3

script:
  - |
    php -S localhost:8080 -t web > /dev/null 2>&1 &
    vendor/bin/codecept run
