language: php

php:
  - 5.6
  - 7.0
#  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.1"
  - travis_retry composer update --dev --prefer-dist --no-interaction
# setup application:
  - |
    sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" config/web.php
  # - chmod +x ./tests/travis/setup.sh
  # - ./tests/travis/setup.sh
  # - sudo xvfb-run java -jar $serverFile > /tmp/selenium.log &

  # - java -jar selenium-server-standalone-3.0.1.jar
  # - java -jar -Dwebdriver.gecko.driver=geckodriver selenium-server-standalone-3.0.1.jar &
  - java -jar -Dwebdriver.chrome.driver=chromedriver selenium-server-standalone-3.0.1.jar
  - sleep 20
  - tests/bin/yii serve &
  - sleep 3

script:
  - |
    php -S localhost:8080 -t web > /dev/null 2>&1 &
    vendor/bin/codecept run
